/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BigBtn: typeof import('./src/components/Common/Button/BigBtn.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Home: typeof import('./src/components/Home/index.vue')['default']
    Login: typeof import('./src/components/Login/index.vue')['default']
    LoginBg: typeof import('./src/components/Login/components/LoginBg.vue')['default']
    LoginForm: typeof import('./src/components/Login/components/LoginForm.vue')['default']
    NotFound: typeof import('./src/components/Common/404/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
